name: word_and_memory
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.7.0
  rflutter_alert: ^1.0.3
  percent_indicator: ^2.1.1+1
  fluttertoast: ^4.0.1
  flutter_swiper: ^1.1.6
  flip_card: ^0.4.4

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.15.5+3
  provider: ^4.0.4
  cloud_firestore: ^0.13.4+2
  flutter_spinkit: ^4.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

 
  uses-material-design: true


  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
